job-controllers:
    resource:
        path: ../src/Job/Transport/Controller/Api/
        namespace: App\Job\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json
resume-controllers:
    resource:
        path: ../src/Resume/Transport/Controller/Api/
        namespace: App\Resume\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json
resume-public-controllers:
    resource:
        path: ../src/Resume/Transport/Controller/Frontend/
        namespace: App\Resume\Transport\Controller\Frontend
    type: attribute
    defaults:
        _format: json
